### ISSUE TITLE
Curated codes online

### ISSUE THREAD

**Issue by mkborregaard** [rdmpage/imapgenes#1]
Hi the curated codes are online in my github repository here: https://github.com/mkborregaard/codes-for-published-papers/tree/master/Miraldo%20et%20al.%202016

Since I wrote almost all of the code, it might be more appropriate to just link to my repo in the readme, rather than hosting the codes here.

Best,
Michael Borregaard

**Comment by rdmpage** [comment]
@mkborregaard Thanks for drawing my attention to this, I've added a link to your repository in the README file.

**Comment by mkborregaard** [comment]
Great, thanks for this. I can't see the link though, and it looks like you're still hosting the codes here?

**Comment by rdmpage** [comment]
Whoops, forgot to sync, link should now be visible. Codes still here, lots of copies keeps things safe.

**Comment by mkborregaard** [comment]
It also obscures licensing and provenance, though. If you do want to host the code, you are welcome fork my repo making the provenance clear, rather than opening a new repo under your own profile. Notice I’ve licensed it under the MIT license so you can use it quite freely.

I should say that presently, I’m only concerned about the codes. The data from iMapGenes are a matter that I am not in a position to discuss, though I don’t believe they are released on CC-by or another explictly permissive license.

Best,
Michael
—
____________________________________
Michael Krabbe Borregaard, MSc, PhD
Assistant Professor (TT), Center for Macroecology, Evolution & Climate
Natural History Museum of Denmark, University of Copenhagen
Universitetsparken 15, DK-2100 Copenhagen

Subject Editor, Ecography
Associate Editor, Global Ecology and Biogeography

Featured paper:
Oceanic island biogeography through the lens of the general dynamic model: assessment and prospect<http://onlinelibrary.wiley.com/doi/10.1111/brv.12256/full>, Biological Reviews (2016).
An Anthropocene map of genetic diversity<http://science.sciencemag.org/content/353/6307/1532>, Science (2016)

Fra: Roderic Page <notifications@github.com<mailto:notifications@github.com>>
Svar til: rdmpage/imapgenes <reply@reply.github.com<mailto:reply@reply.github.com>>
Dato: torsdag den 8. juni 2017 kl. 21.05
Til: rdmpage/imapgenes <imapgenes@noreply.github.com<mailto:imapgenes@noreply.github.com>>
Cc: Michael Krabbe Borregaard <mkborregaard@snm.ku.dk<mailto:mkborregaard@snm.ku.dk>>, Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Emne: Re: [rdmpage/imapgenes] Curated codes online (#1)


Whoops, forgot to sync, link should now be visible. Codes still here, lots of copies keeps things safe.

**Comment by rdmpage** [comment]
@mkborregaard  I've deleted the files from this repository, and forked your code. Hope this addresses the concern about provenance. Thanks for making the code accessible.

Regarding the data, there has been some unsatisfactory discussion about making that more widely available (it's already on the Science site behind a paywall and on the imapgenes site). The notion that you can publish a paper by building on existing public domain data (i.e., GenBank) and then not share the derived data strikes me as being at best shortsighted, but that's a discussion for another day.

**Comment by mkborregaard** [comment]
Great, thanks, yes that addresses my concerns.

As I said I'm not really in a position to discuss the data, but in principle I agree completely that openness is a must in science today, and that derivatives of open data should generally also be open (though enforcing this strictly, as e.g. the GPL, is being rejected by a larger and larger portion of the open source community based on the experiences of working with it).

I'm a bit surprised about the suggestion that the data are not shared, as they are available on iMapGenes. There is a big gradient in how data are made openly available in science, ranging from requiring registration and group co-authorship from all deriving publications (the most common form) to putting text files on GitHub. iMapGenes is definitely on the open end of that spectrum, coming with no registration or requirements of any form, other than the user go to the web site and interact with it.
Indeed lots of people are downloading the data and use it - I have interacted with students using it and the codes for projects, and  Dolph Schluter just downloaded the data and codes and published a reanalysis (that can't have taken him more than 45 minutes) in last week's Nature.

The purpose of the website is to make it clear what the data and how they've been processed. It also in principle should open for more collaborations and coordination with us about analysing the data, which is a good thing to my mind. I think it is still up in the air what degree of openness is the best - arguably, the biggest data crisis in science right now is not the lack of downloadable data, but the lack of associated metadata. So much data is being lumped and compared that isn't comparable, and often the users cannot realise it. This is especially concerning for data that is scoured from places like github with automatic web crawlers that disregard metadata.

It may still end up being the preferred approach to just put things on github, but I am not so sure, and I think the community needs some experience with different formats. I do share the general sentiment that openness is a positive ideal in science. Have a good weekend,

Michael
